// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Project URL from the Supabase dashboard (Settings → API). Must use the `VITE_` prefix so Vite exposes it. */
const SUPABASE_URL =
  typeof import.meta.env.VITE_SUPABASE_URL === "string" ? import.meta.env.VITE_SUPABASE_URL.trim() : "";
/** Prefer `anon` / `publishable` key from the dashboard; many templates use `VITE_SUPABASE_ANON_KEY` instead. */
const SUPABASE_PUBLISHABLE_KEY =
  (typeof import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY === "string" ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY.trim() : "") ||
  (typeof import.meta.env.VITE_SUPABASE_ANON_KEY === "string" ? import.meta.env.VITE_SUPABASE_ANON_KEY.trim() : "");

/** False when URL or key is missing — paper trading and watchlist queries should bail out early to avoid opaque network errors. */
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase, isSupabaseConfigured } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://invalid.supabase.local",
  SUPABASE_PUBLISHABLE_KEY || "invalid-placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);